### ISSUE TITLE
Missing comments

### ISSUE THREAD

**Issue by badi02** [will-c-thomas/Genetic-Algorithm-Rubiks-Cube-Solver#1]
I can't completely understand your project, maybe if you add some comment on your files and add description on Read.me filez then I'll understand it.

**Comment by will-c-thomas** [comment]
Old repo, and in general these specific ideas don’t work extremely well together. So, the repo will not be updated further.

**Comment by badi02** [comment]
Hi William can I have your WhatsApp to contact you ?

Le dim. 22 mai 2022 à 03:49, William Thomas ***@***.***> a
écrit :
